Feat/mech support
valory-xyz/mech pull request #160
Opened 2024-02-06 19:34 UTC by 0xArdi

This PR adds support in the mech for the changes proposed in #155 .

2024-02-06 22:03 UTC, DavidMinarsch requested changes

2024-02-06 22:03 UTC, DavidMinarsch commented on packages/valory/skills/task_execution/utils/benchmarks.py
> +import anthropic
Why? That seems strange to include here

2024-02-06 22:03 UTC, DavidMinarsch commented on packages/valory/skills/task_execution/utils/benchmarks.py
> +        return anthropic.Anthropic().count_tokens(text)
The benchmark utils needs to be agnostic to this

2024-02-07 08:10 UTC, 0xArdi commented on packages/valory/skills/task_execution/utils/benchmarks.py
> +import anthropic
Its copied from here https://github.com/valory-xyz/olas-predict-benchmark/blob/main/benchmark/benchmark/utils.py

2024-02-07 10:33 UTC, 0xArdi commented
Req. changes will be addressed in another PR.

2024-02-07 10:33 UTC, merged