Feat/improved tools
valory-xyz/mech pull request #164
Opened 2024-02-09 12:03 UTC by richardblythman

1. Add improved scraping to tools
2. Add RAG tool

2024-02-23 10:48 UTC, richardblythman commented
@jmoreira-valory @Adamantios this is the branch that we need a review on.

2024-02-23 12:49 UTC, 0xArdi commented on tools/prediction_request_rag/prediction_request_rag.py
> +        return results, prediction_prompt, None
The response is expected to be the same across all tools. It has to be (result: str, prompt: str, transaction: Optional[Dict], counter_callback: TokenCounterCallback)

Example: https://github.com/valory-xyz/mech/blob/main/packages/valory/customs/prediction_request/prediction_request.py#L441

2024-02-26 04:48 UTC, moarshy commented on tools/prediction_request_rag/prediction_request_rag.py
> +            model=engine,
done

2024-02-26 04:48 UTC, moarshy commented on tools/prediction_request_rag/prediction_request_rag.py
> +        return results, prediction_prompt, None
done

2024-02-26 14:29 UTC, jmoreira-valory requested changes
Please merge main branch here and structure the tools under 
`packages/<vendor>/customs/<custom_package_name>`

2024-02-27 21:40 UTC, jmoreira-valory approved these changes

2024-02-27 21:44 UTC, jmoreira-valory commented
Note: This PR has been restructured to be merge ready with the new structure of the packages directory:

1. Main branch has been merged here
2. Each tool has been moved to their corresponding location under `packages/vendor/customs/tool`
3. The source code of the tools has been updated to the latest changes in this branch at commit https://github.com/valory-xyz/mech/pull/164/commits/da70f350734189e929ddb2019477ffd3af384b68 (already merged changes in main will therefore be hidden).
4. Hashes have been updated.

2024-02-28 09:33 UTC, Adamantios commented on packages/napthaai/customs/prediction_request_rag/prediction_request_rag.py
> +        return results, prediction_prompt, None, None
```suggestion
        return results, prediction_prompt, None, counter_callback

```

2024-02-28 09:35 UTC, Adamantios commented on packages/nickcom007/customs/prediction_request_sme/prediction_request_sme.py
> +    text
Can you explain this line?

2024-02-28 09:38 UTC, Adamantios commented on packages/valory/customs/prediction_request/prediction_request.py
> +    return additional_information, None
```suggestion
    return additional_information, counter_callback
```

2024-02-28 09:39 UTC, Adamantios commented on packages/valory/customs/prediction_request_claude/prediction_request_claude.py
> +    num_words: Optional[int] = 300,
Maybe default to `None`?

2024-02-28 09:40 UTC, Adamantios commented on packages/valory/customs/prediction_request_claude/prediction_request_claude.py
> +    return additional_information, None
```suggestion
    return additional_information, counter_callback
```

2024-02-28 09:45 UTC, moarshy commented on packages/nickcom007/customs/prediction_request_sme/prediction_request_sme.py
> +    text
This seem to be missing something. it should have been

`text = md(text, heading_style="ATX")`

2024-02-28 09:56 UTC, moarshy commented on packages/valory/customs/prediction_request_claude/prediction_request_claude.py
> +        return " ".join(text.split()[:num_words])
no, maybe can bring the first split below.

2024-02-28 09:56 UTC, moarshy commented on packages/valory/customs/prediction_request_claude/prediction_request_claude.py
> +    num_words: Optional[int] = 300,
ok

2024-02-28 13:21 UTC, Adamantios approved these changes

2024-02-28 15:27 UTC, 0xArdi approved these changes

2024-02-28 19:24 UTC, merged