add answers for invalid and not enough info to resolve market
valory-xyz/mech pull request #186
Opened 2024-03-07 09:00 UTC by richardblythman

2024-03-07 10:14 UTC, Adamantios approved these changes

2024-03-07 16:16 UTC, Adamantios approved these changes

2024-03-07 17:14 UTC, 0xArdi commented on packages/napthaai/customs/resolve_market_reasoning/resolve_market_reasoning.py
> +                return determinable_results, reasoning, additional_information, queries, None
`determinable_results`should be a string

2024-03-07 17:15 UTC, 0xArdi requested changes
Please confirm the return type. Otherwise, looks good.

2024-03-08 14:48 UTC, richardblythman commented
@0xArdi should be good to go

2024-03-08 15:09 UTC, 0xArdi approved these changes

2024-03-08 15:09 UTC, merged