Enhancements and New Feature Implementation: Fix rag and new tools
valory-xyz/mech pull request #188
Opened 2024-03-12 14:02 UTC by moarshy

This PR encompasses the following updates:

1. **Bug Fixes for Prediction-Request RAG Tool**: We've identified and resolved several issues affecting the prediction-request RAG tool, enhancing its stability and performance. These fixes address bugs that were impacting the tool's accuracy.

2. **Conversion of Market Reasoning Tool**: The market reasoning tool has been doing very well on the benchmark. We have converted that into a tool for the trader under `prediciton_request_reasoning`.

3. **New Tool: Chain of Thought Document Analysis**: We have had some success with a new tool implementing COT on document/article retrieved from single URL. If a prediction is not reached, we will use the next url. This tool also performs well in the benchmark. This is under `prediction_url_cot`

All can be found under napthaai.

Please review the changes and let us know if there is anything.

2024-03-12 14:13 UTC, jmoreira-valory commented on packages/napthaai/customs/prediction_request_rag/prediction_request_rag.py
>          additional_information, counter_callback = fetch_additional_information(
Shouldn't pass temperature and max_tokens here as well?

2024-03-12 14:36 UTC, Adamantios reviewed
LGTM, can you link the benchmark's results for `prediction_url_cot` in the description for reference?

2024-03-18 15:30 UTC, jmoreira-valory commented on packages/napthaai/customs/prediction_url_cot/prediction_url_cot.py
> +def run(**kwargs) -> Tuple[str, Optional[Dict[str, Any]]]:
Please fix the interface to match the requirements in https://github.com/valory-xyz/mech/blob/main/README.md#build-your-own

2024-03-18 15:31 UTC, jmoreira-valory commented on packages/napthaai/customs/prediction_url_cot/prediction_url_cot.py
> +        return results, prediction_prompt, None, counter_callback
Fix to match the interface.

2024-03-18 15:31 UTC, jmoreira-valory commented on packages/napthaai/customs/prediction_request_reasoning/prediction_request_reasoning.py
> +def run(**kwargs) -> Tuple[Optional[str], Optional[Dict[str, Any]], Any]:
Fix the interface.

2024-03-18 15:32 UTC, jmoreira-valory commented on packages/napthaai/customs/prediction_request_reasoning/prediction_request_reasoning.py
> +        return results, reasoning_prompt + "////" + prediction_prompt, None, counter_callback
Fix the interface.

2024-03-18 15:34 UTC, jmoreira-valory requested changes
Please, fix the interface of run methods according to https://github.com/valory-xyz/mech/blob/main/README.md#build-your-own, both at definition, and at any `return` statement within. 

Note that second output value is an `Optional[Dict[str, Any]]`, and most times it is wrongly output a string.

A few instances have been marked in the review, but please, verify to cover all of them.

2024-03-21 10:49 UTC, 0xArdi commented on packages/napthaai/customs/prediction_request_rag/prediction_request_rag.py
> +TOOL_TO_ENGINE = {tool: "gpt-3.5-turbo-0125" for tool in ALLOWED_TOOLS}
When running this tool, we get the following error:
```
ValueError: Model gpt-3.5-turbo-0125 not supported.
```

2024-03-21 11:04 UTC, 0xArdi commented on packages/napthaai/customs/prediction_request_reasoning/prediction_request_reasoning.py
> +TOOL_TO_ENGINE = {tool: "gpt-4-0125-preview" for tool in ALLOWED_TOOLS}
Same issue here:
```
ValueError: Model gpt-4-0125-preview not supported.
```

2024-03-21 11:05 UTC, 0xArdi requested changes
There are issues with the new models introduced in this PR. They don't seem to be supported by either the OpenAI library we are using, or the OpenAI API Key we have.

2024-03-21 11:31 UTC, richardblythman commented
I think this should fix the issue @0xArdi

2024-03-21 15:22 UTC, 0xArdi approved these changes

2024-03-21 16:19 UTC, jmoreira-valory commented on packages/packages.json
> +        "custom/napthaai/prediction_request_reasoning/0.1.0": "bafybeiaaefuqy47fv3iuh7qz3yd6ld6fkrt73ixdsilt3uyysr655h3vee",
@0xArdi Why is this a third-party package?

2024-03-26 08:34 UTC, dvilelaf approved these changes

2024-03-26 08:41 UTC, 0xArdi commented on packages/packages.json
> +        "custom/napthaai/prediction_request_reasoning/0.1.0": "bafybeiaaefuqy47fv3iuh7qz3yd6ld6fkrt73ixdsilt3uyysr655h3vee",
it was on accident, has been addressed

2024-03-26 08:47 UTC, jmoreira-valory approved these changes

2024-03-26 08:48 UTC, merged