Add OFV market resolver
valory-xyz/mech pull request #225
Opened 2024-05-07 06:56 UTC by kongzii

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.

## Fixes

If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce? (A **breaking change** is a fix or feature that would cause existing functionality and APIs to not work as expected.)
_Put an `x` in the box that applies_

- [ ] Non-breaking fix (non-breaking change which fixes an issue)
- [ ] Breaking fix (breaking change which fixes an issue)
- [ ] Non-breaking feature (non-breaking change which adds functionality)
- [ ] Breaking feature (breaking change which adds functionality)
- [ ] Refactor (non-breaking change which changes implementation)
- [ ] Messy (mixture of the above - requires explanation!)

## Checklist

_Put an `x` in the boxes that apply._

- [ ] I have read the [CONTRIBUTING](../blob/main/CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `main` branch (left side). Also you should start your branch off our `main`.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-05-07 07:18 UTC, kongzii commented on pyproject.toml
> +open-autonomy = { git = "https://github.com/kongzii/open-autonomy.git", rev = "13344d6551222224492024623cd10aa79ad1a13e" }
What's the plan for the dependency updates in related repositories, please?

And I know Evan was working on some dependency-related stuff as well, I'll get in touch with him about the current status.

2024-05-07 08:09 UTC, 0xArdi commented on pyproject.toml
> +open-autonomy = { git = "https://github.com/kongzii/open-autonomy.git", rev = "13344d6551222224492024623cd10aa79ad1a13e" }
What's the issue you're facing? Did you have to make adjustments to open-autonomy? If so, feel free to make a PR on the [main open-autonomy repo](https://github.com/valory-xyz/open-autonomy), we can take a look.

2024-05-07 08:12 UTC, kongzii commented on pyproject.toml
> +open-autonomy = { git = "https://github.com/kongzii/open-autonomy.git", rev = "13344d6551222224492024623cd10aa79ad1a13e" }
Yes, PR for open-autonomy is open: https://github.com/valory-xyz/open-autonomy/pull/2223
And for tomte too: https://github.com/valory-xyz/tomte/pull/27

The issue we are facing is that with current strict versioning, it's almost impossible to use it with other libraries.

2024-05-08 09:18 UTC, kongzii commented
@richardblythman Could you please explain why this pattern of doing `def run(**kwargs)` is necessary? I saw it in other tools as well but I didn't understand, because from the caller's perspective, having

```
def run(**kwargs): ...
```

or having

```
def run(
  prompt: str,
  api_keys: dict[str, str],
): ...
```

is called in the same way by doing `run(prompt=..., api_keys=...)`. But in the second way it cleaner what arguments the function expects and what types.

2024-05-08 09:22 UTC, richardblythman commented
```
def run(
  prompt: str,
  api_keys: dict[str, str],
): ...
```

I think this would have worked, but it's not what you had originally.

2024-05-08 09:26 UTC, kongzii commented
> I think this would have worked, but it's not what you had originally.

@richardblythman  Yeah, I see the changes in arguments, that's clear to me that it needs to have the same interface as other tools to make it simpler for calling from agents/mech. I just didn't understand why the **kwargs.

2024-05-08 09:30 UTC, richardblythman commented
@kongzii I just copied and pasted. Not sure if the team at Valory prefer one over the other.

2024-05-23 08:08 UTC, jmoreira-valory commented on pyproject.toml
> +sentence-transformers = "^2.1.0"
This package is causing license compatibility issues on the sub-dependencies. This should be corrected.

2024-05-24 08:16 UTC, jmoreira-valory requested changes
- License is not compatible.
- Ensure tool outputs (possibly configurable) "is_valid = false" when dealing with invalid markets. (Similar to https://github.com/valory-xyz/mech/blob/main/packages/napthaai/customs/resolve_market_reasoning/resolve_market_reasoning.py)

2024-05-24 13:50 UTC, 0xArdi commented
@kongzii can you resolve the merge conflicts?

2024-05-24 14:42 UTC, kongzii commented
Hey, thanks for the reviews! I'll take a look at all of this next week 🙏 👌

2024-05-29 08:39 UTC, kongzii commented
Hey @jmoreira-valory @0xArdi , about the changes:

> can you resolve the merge conflicts?

Resolved here and on the related PRs as well.

> Ensure tool outputs (possibly configurable) "is_valid = false" when dealing with invalid markets.

Added ✅ 

> Please, only use released versions of repos. Please, send a PR to the required repositories if any change is required in them.

Yes, they are linked above in the comment, as soon as you release them I'll update this PR 🙏 

https://github.com/valory-xyz/tomte/pull/27 and https://github.com/valory-xyz/open-autonomy/pull/2223

> License is not compatible.

What error do you see, please? I can not see any pipeline being executed on this PR. And when I try to run `tox -e liccheck ` locally I see this, but that's. about another package that was already used:

![Screenshot by Dropbox Capture](https://github.com/valory-xyz/mech/assets/15619339/a3c39db8-6370-4376-806c-28796f219dc3)

And https://github.com/UKPLab/sentence-transformers uses Apache 2.0, same as mech repository.

2024-06-07 09:12 UTC, dvilelaf commented
@kongzii not sure if this liccheck failure comes from another PR, but just in case you want to solve it, I've checked that replicate follows an Apache license so that's ok (liccheck seems to miss that), so adding replicate to the Authorized packages section on tox.ini will do the trick.

2024-06-07 13:35 UTC, 0xArdi commented
@kongzii again some merge conflicts. I'll merge as soon as they are resolved.

2024-06-07 13:37 UTC, 0xArdi commented
As for the CI, I will address as there are issues unrelated to this PR.

2024-06-24 11:32 UTC, dvilelaf commented
@kongzii will you be able to merge main and resolve conflicts so we can merge this PR?

2024-06-25 06:25 UTC, kongzii commented
@dvilelaf Unfortunately I can't, there was [this PR merged in the meantime](https://github.com/valory-xyz/mech/pull/237/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R77) that adds `prediction-market-agent-tooling` as a dependency, but from a branch `gabriel/olas`. I have some library conflicts now as well, but I am waiting for @gabrielfior to resolve his first and do a proper release before I integrate mine.

@gabrielfior any time estimate on that, please?

2024-06-25 08:41 UTC, gabrielfior commented
> @gabrielfior any time estimate on that, please?

Once the PR below is completed, I expect that you will be able to merge this as well.
https://github.com/gnosis/prediction-market-agent-tooling/issues/281

2024-06-25 08:48 UTC, kongzii commented
@gabrielfior It seems like the subgrounds guys merged your PR, so could you please continue on it? It also blocks me from adding image generation to the mech.

2024-06-25 08:58 UTC, gabrielfior commented
> @gabrielfior It seems like the subgrounds guys merged your PR, so could you please continue on it? It also blocks me from adding image generation to the mech.

https://github.com/gnosis/prediction-market-agent-tooling/pull/285

2024-06-27 10:49 UTC, kongzii commented
Conflicts are resolved now; however, merging should wait for https://github.com/valory-xyz/mech/pull/241 to be merged first to not create conflicts.

And `open-autonomy` + `tomte` are still installed from git commit instead of versioned release, is that okay?

2024-07-03 13:59 UTC, jmoreira-valory commented on pyproject.toml
> +open-autonomy = { git = "https://github.com/kongzii/open-autonomy.git", rev = "0a879f7f5ad6d4348f8f59610da9c70a4e9a9a10" }
@0xArdi please validate this.

2024-07-03 13:59 UTC, jmoreira-valory commented on pyproject.toml
> +en_core_web_sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl" }
@0xArdi please validate this.

2024-07-03 14:50 UTC, jmoreira-valory commented on pyproject.toml
> +tomte = {git = "https://github.com/kongzii/tomte.git", rev = "a4f7cac233c25494742feb1531305ec99fb7f721", extras = ["cli", "tests"]}
@0xArdi validate.

2024-07-04 12:59 UTC, 0xArdi commented
@kongzii any reason why you are using the forks as deps?

2024-07-04 17:26 UTC, kongzii commented
@0xArdi I already linked PRs for tomte and open-autonomy forks above https://github.com/valory-xyz/mech/pull/225#discussion_r1592001201. OpenFactVerifier is installed from git because they don't have a pypi package published.

2024-07-05 09:57 UTC, 0xArdi commented on pyproject.toml
> +open-autonomy = { git = "https://github.com/kongzii/open-autonomy.git", rev = "13344d6551222224492024623cd10aa79ad1a13e" }
If we were to merge this, it means that we need to keep using your fork until we reflect your changes on our framework.

2024-07-05 09:58 UTC, 0xArdi commented
@kongzii there is an issue with the nvidia licenes, there are some libs that have `NVIDIA Proprietary Software` licence, which is not compatible with the licence of the mech. Is there something you can do about that?

2024-07-05 10:02 UTC, kongzii commented on pyproject.toml
> +open-autonomy = { git = "https://github.com/kongzii/open-autonomy.git", rev = "13344d6551222224492024623cd10aa79ad1a13e" }
Then maybe you could merge and release changes in these two PRs so I can use them properly here?

2024-08-07 15:05 UTC, merged