DALL-E request mech tool
valory-xyz/mech pull request #239
Opened 2024-06-11 04:58 UTC by victorpolisetty

## Proposed changes

Adding DALL-E as a mech tool. To be utilized as a text to image generation tool.

## Fixes

N/A

## Types of changes

What types of changes does your code introduce? (A **breaking change** is a fix or feature that would cause existing functionality and APIs to not work as expected.)
_Put an `x` in the box that applies_

- [ ] Non-breaking fix (non-breaking change which fixes an issue)
- [ ] Breaking fix (breaking change which fixes an issue)
- [x] Non-breaking feature (non-breaking change which adds functionality)
- [ ] Breaking feature (breaking change which adds functionality)
- [ ] Refactor (non-breaking change which changes implementation)
- [ ] Messy (mixture of the above - requires explanation!)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](../blob/main/CONTRIBUTING.md) doc
- [x] I am making a pull request against the `main` branch (left side). Also you should start your branch off our `main`.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works

## Further comments

There is currently OpenAI GPT support but no DALL-E support

2024-06-21 10:19 UTC, 0xArdi requested changes
Changes look good @victorpolisetty . Can you add a test like here: https://github.com/valory-xyz/mech/blob/main/tests/test_tools.py#L106

2024-06-23 22:45 UTC, victorpolisetty commented
Added unit test

2024-06-24 11:18 UTC, dvilelaf approved these changes

2024-07-02 10:18 UTC, 0xArdi approved these changes

2024-07-02 10:19 UTC, merged