Featuring SQ mech tool
valory-xyz/mech pull request #240
Opened 2024-06-11 19:15 UTC by bgodlin

## Proposed changes

Introducing a new mech tool

## Fixes

N/A

## Types of changes

What types of changes does your code introduce? (A **breaking change** is a fix or feature that would cause existing functionality and APIs to not work as expected.)
_Put an `x` in the box that applies_

- [ ] Non-breaking fix (non-breaking change which fixes an issue)
- [ ] Breaking fix (breaking change which fixes an issue)
- [x] Non-breaking feature (non-breaking change which adds functionality)
- [ ] Breaking feature (breaking change which adds functionality)
- [ ] Refactor (non-breaking change which changes implementation)
- [ ] Messy (mixture of the above - requires explanation!)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](../blob/main/CONTRIBUTING.md) doc
- [x] I am making a pull request against the `main` branch (left side). Also you should start your branch off our `main`.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works

## Further comments

N/A

2024-06-21 10:14 UTC, 0xArdi requested changes
Looks good @bgodlin . Can you please add at least 1 test? 
Example here: https://github.com/valory-xyz/mech/blob/main/tests/test_tools.py#L106

2024-06-24 11:15 UTC, dvilelaf commented
@bgodlin will you be able to address the comment from Ardian?

2024-07-02 14:56 UTC, 0xArdi commented
@bgodlin can you address merge conflicts?

2024-07-29 11:09 UTC, 0xArdi commented on tests/subquery/examples.py
> +query_examples = """
copyright header is missing here, which the CI complains about

2024-07-29 11:11 UTC, 0xArdi commented on packages/subquery/customs/graphql_response_analyser/component.yaml
> +    version: ==0.5.1
```suggestion
  openai:
    version: ==1.11.0
  tiktoken:
    version: ==0.5.1
  requests: {}
```

2024-07-29 11:12 UTC, 0xArdi commented on packages/subquery/customs/graphql_response_analyser/component.yaml
> +    version: ==0.5.1
CI complains about this

2024-07-29 11:12 UTC, 0xArdi requested changes
A couple of required changes to address CI failures

2024-08-01 15:48 UTC, 0xArdi commented on packages/subquery/customs/graphql_response_analyser/component.yaml
> +name: graphql_response_analyser
there are some missing required fields here:
```
aea.exceptions.AEAValidationError: The following errors occurred during validation:
 - : 'fingerprint' is a required property
 - : 'fingerprint_ignore_patterns' is a required property
 ```

2024-08-01 15:48 UTC, 0xArdi requested changes
some more check failures, i left a comment what needs to be changed

2024-11-22 14:47 UTC, 0xArdi commented
We are in the process of migrating the project to a [new](https://github.com/valory-xyz/mech-predict) location. 
As part of the transition, we are **closing your open pull request**.
- **No new tool PRs will be merged here**.
- This repo will only contain a bare minimum set of the dependencies. This repo will serve as a base repo for people looking to develop their own mechs and follow this as an example in the future.
- We invite you to go through our [quickstart](https://github.com/valory-xyz/mech-quickstart) on how to setup your mech and tools.

Thank you for your contributions!

2024-11-22 14:47 UTC, closed without merging